object_preselection:
  Jet:
    pt_raw: 15
    eta: 4.7 
    jetId: 0

  JetCorrMET:
    pt: 15
    EmEF: 0.9 
    eta: 5.2

  JetPNetCorrMET:
    pt: 15
    EmEF: 0.9 
    eta: 5.2

  JetPNetPlusNeutrinoCorrMET:
    pt: 15
    EmEF: 0.9 
    eta: 5.2

  GenJet:
    pt: 8 
    eta: 10 
    
  Muon:
    pt: 10
    eta: 2.4
    dxy: 0.045
    dz: 0.2
    id: mediumId
    iso: 0.15

  Electron:
    pt: 15
    eta: 10
    iso: 0.06
    id: mvaIso_WP80