name: pocket-coffea-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.23.5
  - scipy=1.13.1
  - numba=0.60.0
  - onnxruntime=1.19.2
  - awkward>=1.10.3,<2
  - pandas=2.3.0
  - matplotlib=3.9.4
  - dask=2024.8.0
  - distributed=2024.8.0
  - dask-jobqueue=0.8.5
  - correctionlib=2.7.0
  - pyarrow=20.0.0
  - xrootd=5.8.1
  - lz4
  - tqdm
  - pip
  - pip:
      - coffea==0.7.29
      # Put the path to your PocketCoffea repository
      - -e ../PocketCoffea
      - -e ./
      # Add any other pip-only packages here, but avoid numpy, scipy, numba, awkward, coffea, etc.
