# Commented triggers means it's not yet clear if they will be used in the final analysis

HLT_triggers:
   "2022_preEE":
      JetMET:
         - QuadPFJet70_50_40_35_PFBTagParticleNet_2BTagSum0p65
   "2022_postEE":
      JetMET:
         - QuadPFJet70_50_40_35_PFBTagParticleNet_2BTagSum0p65
   "2023_preBPix":
      JetMET0:
         - HLT_QuadPFJet70_50_40_35_PNet2BTagMean0p65
      JetMET1:
         - HLT_QuadPFJet70_50_40_35_PNet2BTagMean0p65
      ParkingHH:
         - PFHT280_QuadPFJet30_PNet2BTagMean0p55
   "2023_postBPix":
      JetMET0:
         - HLT_QuadPFJet70_50_40_35_PNet2BTagMean0p65
      JetMET1:
         - HLT_QuadPFJet70_50_40_35_PNet2BTagMean0p65
      ParkingHH:
         - PFHT280_QuadPFJet30_PNet2BTagMean0p55
   "2024":
      ParkingHH:
         - PFHT250_QuadPFJet25_PNet2BTagMean0p55
